// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDedrOa3POGTdj2JmVKbWXpFGqXKMIuDQk',
    appId: '1:796275430988:android:80fffe34b88386878786e9',
    messagingSenderId: '796275430988',
    projectId: 'flutter-onjung-project-6d13f',
    storageBucket: 'flutter-onjung-project-6d13f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe3FCdY0kSJPzg2pery8HVVtMA0WUAnsk',
    appId: '1:796275430988:ios:454e8d75bf0b5db08786e9',
    messagingSenderId: '796275430988',
    projectId: 'flutter-onjung-project-6d13f',
    storageBucket: 'flutter-onjung-project-6d13f.firebasestorage.app',
    iosClientId: '796275430988-eieam1n6c5kl9ks98thha5a060b688ef.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterOnjungV1',
  );
}
